name: "Docker push to GCR and deploy to GKE"

on:
  push:
    branches:
      - staging
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Image to GCR
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}
      GCR_TAG: ${{ github.run_id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            docker build . -t $IMAGE_NAME/be-production:${GCR_TAG}
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            docker build . -t $IMAGE_NAME/be-staging:${GCR_TAG}
          fi

      - name: Push Docker image
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            docker push $IMAGE_NAME/be-production:${GCR_TAG}
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            docker push $IMAGE_NAME/be-staging:${GCR_TAG}
          fi

  deploy:
    name: Deploy to GKE
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: build
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: wanderai
      NAMESPACE: deploy-gke
      GKE_ZONE: asia-southeast2

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup ENV
        uses: nowactions/envsubst@v1
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GITHUB_RUN_ID: ${{ needs.build.outputs.GCR_TAG }}
        with:
          input: ./deployment_template.yaml
          output: ./deployment.yaml

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Auth GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup GKE
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Print deployment.yaml
        run: cat ./deployment.yaml

      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml
