name: "Docker push to GCR"

on:
  push:
    branches:
      - staging
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Setup Gcloud Account and Deploy the application on Google Cloud
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}
      CLUSTER_NAME: wanderai
      NAMESPACE: deploy-gke
      GKE_ZONE: asia-southeast2

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
      - name: Setup ENV
        uses: nowactions/envsubst@v1
        env:
            PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
            GITHUB_RUN_ID: $GITHUB_RUN_ID
        with:
          input: ./deployment_template.yaml
          output: ./deployment.yaml

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            docker build . -t $IMAGE_NAME/be-production:$GITHUB_RUN_ID
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            docker build . -t $IMAGE_NAME/be-staging:$GITHUB_RUN_ID
          fi

      - name: Push Docker image
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            docker push $IMAGE_NAME/be-production:$GITHUB_RUN_ID
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            docker push $IMAGE_NAME/be-staging:$GITHUB_RUN_ID
          fi

      - name: Auth GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          
      - name: Setup GKE
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: $CLUSTER_NAME
          location: 'asia-southeast2'
          project_id: ${{ secrets.GCP_PROJECT_ID }}


      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml